/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        error: "#ffb4ab",
        "tertiary-fixed": "#ffdbcd",
        "secondary-container": "#0566d9",
        "primary-fixed-dim": "#b4c5ff",
        "on-error-container": "#ffdad6",
        "on-surface": "#e4e1e9",
        "inverse-surface": "#e4e1e9",
        "inverse-on-surface": "#303036",
        outline: "#8d90a0",
        "surface-container-low": "#1b1b20",
        "secondary-fixed": "#d8e2ff",
        "tertiary-container": "#bc4800",
        "surface-container": "#1f1f25",
        "surface-dim": "#131318",
        "surface-container-lowest": "#0e0e13",
        "outline-variant": "#434655",
        "inverse-primary": "#0053db",
        "on-secondary": "#002e6a",
        "on-surface-variant": "#c3c6d7",
        "on-secondary-fixed": "#001a42",
        "surface-container-high": "#2a292f",
        "on-background": "#e4e1e9",
        secondary: "#adc6ff",
        "surface-tint": "#b4c5ff",
        "on-tertiary-container": "#ffede6",
        "surface-bright": "#39383e",
        "on-primary-fixed-variant": "#003ea8",
        primary: "#b4c5ff",
        tertiary: "#ffb596",
        "on-tertiary": "#581e00",
        "primary-fixed": "#dbe1ff",
        "on-primary-fixed": "#00174b",
        "on-secondary-container": "#e6ecff",
        "secondary-fixed-dim": "#adc6ff",
        surface: "#131318",
        background: "#131318",
        "on-error": "#690005",
        "on-tertiary-fixed": "#360f00",
        "on-primary": "#002a78",
        "error-container": "#93000a",
        "surface-variant": "#35343a",
        "surface-container-highest": "#35343a",
        "on-secondary-fixed-variant": "#004395",
        "primary-container": "#2563eb",
        "tertiary-fixed-dim": "#ffb596",
        "on-tertiary-fixed-variant": "#7d2d00",
        "on-primary-container": "#eeefff",
        // Landing Page tokens
        brand: "#2563eb",
        canvas: "#0A0A0F",
        subtle: "#161622",
        borderLine: "#1E1E2A",
        textPrimary: "#EDEDF0",
        textSecondary: "#888896",
        textMuted: "#5F5F70",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      fontFamily: {
        "code-lg": ["JetBrains Mono", "monospace"],
        "body-md": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "headline-lg": ["Inter", "sans-serif"],
        "code-md": ["JetBrains Mono", "monospace"],
        "code-sm": ["JetBrains Mono", "monospace"],
        "headline-xl": ["Inter", "sans-serif"],
        "headline-sm": ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "body-xs": ["Inter", "sans-serif"],
      },
      fontSize: {
        "code-lg": ["14px", { lineHeight: "22px", fontWeight: "500" }],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "headline-md": ["16px", { lineHeight: "24px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "label-sm": ["11px", { lineHeight: "14px", letterSpacing: "0.04em", fontWeight: "500" }],
        "body-sm": ["13px", { lineHeight: "18px", fontWeight: "400" }],
        "headline-lg": ["20px", { lineHeight: "28px", letterSpacing: "-0.015em", fontWeight: "600" }],
        "code-md": ["13px", { lineHeight: "20px", fontWeight: "400" }],
        "code-sm": ["12px", { lineHeight: "18px", fontWeight: "400" }],
        "headline-xl": ["24px", { lineHeight: "32px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "headline-sm": ["14px", { lineHeight: "20px", letterSpacing: "-0.005em", fontWeight: "600" }],
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.02em", fontWeight: "500" }],
        "body-xs": ["12px", { lineHeight: "16px", fontWeight: "400" }],
      }
    },
  },
  plugins: [],
}
